/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainProject.Statiscial;

import MainProject.Order.OrderOff;
import com.mysql.cj.Constants;
import javax.swing.JButton;
import MainProject.DAO.Constant;
import MainProject.DAO.StatiscalModify;
import MainProject.DAO.bookModify;
import static MainProject.Statiscial.OrderdetailFrame.address;
import static MainProject.Statiscial.OrderdetailFrame.check;
import static MainProject.Statiscial.OrderdetailFrame.id;
import static MainProject.Statiscial.OrderdetailFrame.name;
import static MainProject.Statiscial.OrderdetailFrame.phone;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author ASUS
 */
public class ModelStaticalFrame extends javax.swing.JFrame implements Runnable{
    List<OrderOff> dataList;
    List<String> day = new ArrayList<>();
    int setTotal[];
    private Thread thread;
    public static boolean check = false;
    public static String setDate = "";
    /**
     * Creates new form TestFrame
     */
    public ModelStaticalFrame() {
        initComponents();
        setTitle("Modal Month");
        setResizable(false);//Ko định lại kích thước giao diện
        setLocationRelativeTo(null);//Ra giũa màn hình
        Start();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
       
    }
    
    private void getDaY(String s) {
         List<String> date = new ArrayList<>();
         List<String> withoutdate = new ArrayList<>();
         dataList = StatiscalModify.Search(s);
         for(OrderOff od : dataList) { 
            String date1 = getDate(od.getCreated_at());
            withoutdate.add(date1);
        }
        for(String element : withoutdate) {
            if(!day.contains(element)) {
                day.add(element);
            }
        }
        setTotal = new int[day.size()];
        for(OrderOff od : dataList) {
             String date1 = getDate(od.getCreated_at());
             for(int i = 0; i < day.size(); i++) {
                 if(date1.equals(day.get(i))) {
                     setTotal[i] += od.getTotalPrice();
                 }
             }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new javax.swing.BoxLayout(MainPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMain.setForeground(new java.awt.Color(255, 255, 255));
        labelMain.setText("Thống kê");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(labelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Start() {
        if (thread == null) {
            thread = new Thread(this);
            thread.start();
        }
    }
    
    private String getDate(String s) {
        String[] array = s.replace("-", " ").split("\\s");
        return array[2];
    }
    
    private String getMonth(String s) {
        String[] array = s.replace("-", " ").split("\\s");
        return array[1];
    }    
    
    private void setModel(String s, String month) {
        getDaY(s);
        DefaultCategoryDataset dc = new DefaultCategoryDataset();
        for(int i = 0; i < day.size(); i++) {
            dc.setValue(setTotal[i], "Month " + month, day.get(i) +"-"+ month);
        }
        
        JFreeChart jchart = ChartFactory.createBarChart3D("", "Date", "Total Price", dc, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.red);
        
        ChartPanel chartPanel = new ChartPanel(jchart);
        MainPanel.removeAll();
        MainPanel.add(chartPanel);
        MainPanel.updateUI();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModelStaticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModelStaticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModelStaticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModelStaticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModelStaticalFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMain;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            if(check) {
              String month = getMonth(setDate);
                setModel(setDate, month);
                check = false;
                labelMain.setText("Thống kê tháng " + month);
            }
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
